#cloud-config
package_update: true

yum_repos:
  AmazonCorretto:
    baseurl: https://yum.corretto.aws/$basearch
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: https://yum.corretto.aws/corretto.key
    name: Amazon Corretto

packages:
  - java-17-amazon-corretto-devel.x86_64
  - yum-cron
  - wget
  - awscli
  - jq
  - bzip2

write_files:
  - content: ${minecraft-service}
    encoding: b64
    path: /etc/systemd/system/minecraft.service
  - content: ${minecraft-cron}
    encoding: b64
    path: /etc/cron.d/minecraft
  - content: eula=true
    path: ${mc_root}/eula.txt
  - path: /etc/environment
    content: |
      SSH_USER="ec2-user"
      MINECRAFT_JAR="minecraft-server.jar"
      RESTIC_REPOSITORY="s3:s3.${aws_region}.amazonaws.com/${mc_bucket}/restic"
      RESTIC_PASSWORD="${restic_password}"
      AWS_DEFAULT_REGION="${aws_region}"
    append: true

runcmd:
  - wget -O /home/$SSH_USER/backup.sh https://github.com/nicolaschan/minecraft-backup/releases/latest/download/backup.sh
  - chmod +x /home/$SSH_USER/backup.sh
  - [
      "sed",
      "-i",
      "-e",
      "s/emit_via = stdio/emit_via = email/",
      "-e",
      "s/apply_updates = no/apply_updates = yes/",
      "-e",
      "s/update_cmd = default/update_cmd = security/",
      "/etc/yum/yum-cron.conf",
    ]
  - chkconfig yum-cron on
  - service yum-cron start
  - yum upgrade -y
  - curl -L https://github.com/restic/restic/releases/download/v0.12.1/restic_0.12.1_linux_amd64.bz2 | bunzip2 > /usr/bin/restic
  - chmod 750 /usr/bin/restic
  - restic init
  - systemctl enable minecraft
  - mkdir -p ${mc_root}
  - wget -O ${mc_root}/$MINECRAFT_JAR ${server_url}
  - sleep 5
  - chown -R $SSH_USER ${mc_root}
  - systemctl start minecraft
